const DOCUMENT_NOT_FOUND_ERROR = 404;
const CAST_ERROR = 400;
const VALIDATION_ERROR = 400;
const DEFAULT_ERROR = 500;

module.exports = {
  DOCUMENT_NOT_FOUND_ERROR,
  CAST_ERROR,
  VALIDATION_ERROR,
  DEFAULT_ERROR,
};
