const DOCUMENT_NOT_FOUND_ERROR = 404;
const CAST_ERROR = 400;
const VALIDATION_ERROR = 400;
const DEFAULT_ERROR = 500;
const UNAUTHORIZED_ERROR = 401;
const REQUEST_CONFLICT = 409;
const FORBIDDEN_ERROR = 403;

module.exports = {
  DOCUMENT_NOT_FOUND_ERROR,
  CAST_ERROR,
  VALIDATION_ERROR,
  DEFAULT_ERROR,
  UNAUTHORIZED_ERROR,
  REQUEST_CONFLICT,
  FORBIDDEN_ERROR,
};
